version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
<<<<<<< HEAD
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 3
=======
>>>>>>> upstream/main
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      include: "scope"
