name: Check Terraform

on:
  push:
    paths:
      - "terraform/**/*.tf"
      - "terraform/**/*.tfvars"
      - ".github/workflows/check-terraform.yml"
  pull_request:
    paths:
      - "terraform/**/*.tf"
      - "terraform/**/*.tfvars"
      - ".github/workflows/check-terraform.yml"

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Install mise and setup
        uses: jdx/mise-action@1648a7812b9aeae629881980618f079932869151 # v4.0.1
        with:
          install: true
          install_args: "terraform"
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize Terraform (without backend)
        run: terraform init -backend=false
        working-directory: terraform

      - name: Format Terraform
        run: terraform fmt -recursive
        working-directory: terraform

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: "Auto fix by workflow"

      - name: Check Terraform
        run: terraform validate && terraform fmt -check -recursive
        working-directory: terraform
