name: Check Terraform

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**/*.tf"
      - "terraform/**/*.tfvars"
      - ".github/workflows/check-terraform.yml"
  pull_request:
    paths:
      - "terraform/**/*.tf"
      - "terraform/**/*.tfvars"
      - ".github/workflows/check-terraform.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: write # push auto-fix commits
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: true

      - name: Install mise and setup
        uses: jdx/mise-action@7e36c90d9ab29c415a2384db3006f3ec8a8cc654 # v4.2.4
        with:
          install: true
          install_args: "aqua:hashicorp/terraform"
          cache: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize Terraform (without backend)
        run: mise run tf-init-nobackend

      - name: Format Terraform
        run: mise run tf-fix

      - name: Commit and Push
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "Auto fix by workflow"

      - name: Check Terraform
        run: mise run tf-check
